[package]
name = "anet-client-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {workspace = true}
rustls = {workspace = true }
log = {workspace = true}
anyhow = {workspace = true}
prost = {workspace = true}
bytes = {workspace = true}
quinn = {workspace = true }
rustls-pemfile = {workspace = true}
rand = { workspace = true }
x25519-dalek = {workspace = true}
ed25519-dalek = {workspace = true}
base64 = {workspace = true}
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }


anet-common = { path = "../anet-common" }

[lib]
path = "src/lib.rs"
